---
- name: Gather System Information and Create HTML Report
  hosts: all
  become: true
  tasks:
    - name: Gather User Information
      shell: getent passwd
      register: users_info

    - name: Gather Hostname and DNS Name
      shell: hostname
      register: system_info

    - name: Gather IP Address
      shell: ip a | grep "x.x."
      register: network_info

    - name: Gather Disk Usage
      shell: df -h
      register: disk_info

    - name: Gather Uptime
      shell: uptime
      register: uptime_info

    - name: Gather Memory Usage
      shell: free -m
      register: memory_info

    - name: Gather Kernel Number
      debug:
        var: ansible_facts.bios_version
      register: os_info
      
    - name: Kernal infos
      shell: uname -a
      register: kernel_info
    
    - name: Create HTML Report
      template:
        src: /darren_ansible/template/main.html.j2
        dest: /var/www/html/login.html
      delegate_to: localhost

    - name: Create HTML Report
      template:
        src: /darren_ansible/template/system_info_template.html.j2
        dest: "/var/www/html/system_info_{{ inventory_hostname }}.html"
      loop: "{{ ansible_play_batch }}"
      delegate_to: localhost

    - name: Create index Report
      template:
        src: /darren_ansible/template/index.html.j2
        dest: "/var/www/html/index.html"
      delegate_to: localhost 
